# Generated by Django 5.0.6 on 2024-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата отправки последнего напоминания",
            ),
        ),
    ]
